server:
  port: 8082
  servlet:
    context-path: /
spring:
  #数据库连接配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: root

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sentinel.login.loginsoa.model
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

## 日志配置
logging:
  config: classpath:slf4j.xml
  level:
    com.sentinel.login.loginsoa: trace

